### ISSUE TITLE
Doesn't show right-to-left text properly

### ISSUE THREAD

**Issue by TheWeirdDev** [sevenuz/gnome-translate-indicator#1]
The extension has an issue with RTL languages (Persian, Hebrew, Arabic, etc...)
It shows the RTL text backwards and it's hardly readable:

![image](https://user-images.githubusercontent.com/6321734/89169452-81a1e100-d593-11ea-8c57-c71e3593db83.png)

<left>
For example ب‌و‌خ should be shown as خوب
</left>

Thanks for the useful extension.

**Comment by TheWeirdDev** [comment]
Seems like the `-no-bidi` option for translate-shell fixes this issue.
https://github.com/soimort/translate-shell/issues/288

I tried adding it to the 'Default translate options' but nothing changed.

**Comment by sevenuz** [comment]
Hi, sorry for the late reply. Does is it still not work? For me the translation changes with the -no-bidi function. But maybe i could reproduce it with your trans parameters.

**Comment by TheWeirdDev** [comment]
Hi, adding that option in the settings didn't work but i added it inside the extension textbox and it worked. I am currently running gnome-shell 3.38 and the extension is not compatible anymore.

**Comment by sevenuz** [comment]
Yes i fixed [the problem](https://github.com/sevenuz/gnome-translate-indicator/issues/2) but the update needs a review on the gnome extension page :)
You can apply instantly the update by using this repo.
