### ISSUE TITLE
Indicator Colors, Mouse and Options

### ISSUE THREAD

**Issue by ajowens001** [sevenuz/gnome-translate-indicator#4]
Hello.  Awesome applet.  Just want to let someone know that I've experienced a couple issues since install.

The indicator applet works.  I really love the ability to translate from shell; and I only just started using the trans tool with CLI yesterday.

Anyway...
Issues are as follows...

Mouse:  The search boxes (and any other input boxes, it seems) will not keep focus for text entry.  As soon as the cursor leaves the small area for entering text, the progress of text entry is totally lost and the user is required to click in there and start typing again.

This isn't such a big deal, the applet stiill functions.  However, since install I've already found myself getting incredibly frustrated with myself for not keeping my cursor inside the text entry boxes.  As an aspiring developer with a small case of OCD and attention issues which result from too much attention to detail; this is amazing and I can't wait to dive in a find out the reason.  Walking around in the general user's shoes for a while, I'd like to point out that making users frustrated with a development is going backwards.  I only mention this to facilitate prioritizing fixes/patches.

Colors:  The colors of the text inside the boxes without focus is fine.  The colors of the text inside the boxes with focus is a whole other story.

Once I was finally able to determine where to enter my search text; upon trying to click into the search box, I noticed that the color of the text already in there was way too hard to see.  When I manage to find the place to click+drag for highlight of trans options, the text goes to black again and I can easily see where I want to add/replace text/options.  You can see this in the relative screenshot provided.  The first two search boxes seen when the user opens the indicator applet behave as expected - except for the mouse/focus problem mentioned above.
A thought that occurs to me is that this _may_ be because I have a "dark" theme on my system.  Not trying to provide any easy-outs, but if this is the cause, will there be dark theme support in the future?

Options:  Options/flags/arguments do not transfer between the indicator applet and the settings (gnome-shell-extensions) Extensions app.
Once I was able to figure out how to open the Extensions settings for this applet indicator (it's been a while), I was able to find the settings for this app.  I quickly noticed however, that the options selected in those settings do not seem to affect the output at all.  Only the options chosen and typed into the `trans` box (dropdown/delta) inside the applet "Translator Options" will affect output to what was requested.  Please find the attached image for reference to this - and compare it to the other image.  Although the screenshots would help; it would be beneficial for the devs to attempt reproduction of this issue on their machines.

Thank you!  Σας ευχαριστώ!  ありがとうございました！

P.S. 
It would be much appreciated if the devs could give the applet a bit of persistence so that the window doesn't close every time the user clicks-out and shifts focus to another window/application.  This would be a huge benefit to users like me who like to copy translated text and paste translated text and would likely help increase user numbers for the ease of use it facilitates.

![Translate-Indicator options-not-syncing](https://user-images.githubusercontent.com/48398375/200455091-8d1fda35-c79a-4772-b710-989bf2f32bf9.jpg)
![Translate-Indicator dark colors-text](https://user-images.githubusercontent.com/48398375/200455096-497a886c-881e-407e-a70a-0ea684f98235.jpg)

**Comment by sevenuz** [comment]
Hey ajowens, thank you for your detailes issue. I will try to fix it in april. Be free to commit fixes by yourself :) Greetings

**Comment by sevenuz** [comment]
heyho. finally one year later i fixed the extension for gnome 45. there are still some of the issues you mentioned, like the loss of focus. maybe i will look at that. i will not change the behaviour that the menu is closing when you click outside. this is normal for gnome extensions and you may look for a standalone program if you need it. hope you doing good.
