### ISSUE TITLE
Incompatible with gnome 46

### ISSUE THREAD

**Issue by dmnmsc** [sevenuz/gnome-translate-indicator#5]
Hi, 

The extension needs to be updated. Setting "46" in shell-version" throws an error related to `scrollI.add_actor is not a function`

**Comment by sevenuz** [comment]
Thx for reporting, took me a while because I dont use Gnome that often anymore :)
But was very easy to fix with https://gjs.guide/extensions/upgrading/gnome-shell-46.html#gjs

So feel free to make a PR next time :)
Greetings
